#!/bin/bash

#pocet cisel bud zadam nebo 10 :)
if [ $# -lt 1 ];then 
    numbers=10;
else
    numbers=$1;
fi;

((numprocs=numbers+1))

#preklad cpp zdrojaku
mpic++ --prefix /usr/local/share/OpenMPI -o es es.cpp


#vyrobeni souboru s random cisly
dd if=/dev/random bs=1 count=$numbers of=numbers &> /dev/null

#spusteni
mpirun --prefix /usr/local/share/OpenMPI -np $numprocs es

#uklid
rm -f es numbers
